/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

package com.example.executorch.athleticintelligence.squat

import kotlin.math.abs
import kotlin.math.max
import kotlin.math.min

/**
 * metrics for one rep and produces stable rep-level grading. Scoring formulas,
 * weights, and correction-ranking logic are copied verbatim; do not retune.
 */
class RepEvidenceTracker(val repNumber: Int, val view: SquatView) {
    private val frames = mutableListOf<FrameMetrics>()

    /** Mirrors `active_issues`: the alerts generated by the most recently recorded frame. */
    var activeIssues: List<Alert> = emptyList()
        private set

    /** Mirrors `record_frame`. */
    fun recordFrame(metrics: FrameMetrics) {
        frames.add(metrics)
        activeIssues = alertsForFrame(metrics)
    }

    /** Mirrors `_alerts_for_frame`. */
    private fun alertsForFrame(metrics: FrameMetrics): List<Alert> {
        val alerts = mutableListOf<Alert>()
        for ((metric, value) in metrics.values) {
            if (metrics.availability[metric] != MetricAvailability.AVAILABLE) continue
            val rule = METRIC_RULES[metric] ?: continue
            if (metric == "trunk_tibia") {
                if (value <= SquatThresholds.TRUNK_KNEE_W) {
                    val level = levelLe(value, SquatThresholds.TRUNK_KNEE_W, SquatThresholds.TRUNK_KNEE_D)
                    alerts.add(Alert(level, TRUNK_TIBIA_KNEE_DOMINANT_MESSAGE, metric, value, view.label))
                } else if (value >= SquatThresholds.TRUNK_LEAN_W) {
                    val level = levelGe(value, SquatThresholds.TRUNK_LEAN_W, SquatThresholds.TRUNK_LEAN_D)
                    alerts.add(Alert(level, rule.message, metric, value, view.label))
                }
                continue
            }
            val level = levelForValue(value, rule)
            if (level > DangerLevel.SAFE) {
                alerts.add(Alert(level, rule.message, metric, value, view.label))
            }
        }
        return alerts
    }

    /** Mirrors `_level_for_value`. */
    private fun levelForValue(value: Double, rule: MetricRule): DangerLevel {
        return if (rule.lowerIsWorse) {
            levelLe(value, rule.warn, rule.danger)
        } else {
            levelGe(value, rule.warn, rule.danger)
        }
    }

    /** Mirrors `_metric_summary` (dispatches to the metric-specific summaries where applicable). */
    private fun metricSummary(metric: String, rule: MetricRule): MetricSummary {
        val total = frames.size
        val values = frames.mapNotNull { it.value(metric) }
        if (values.isEmpty()) {
            if (
                frames.isNotEmpty() &&
                frames.all { it.availability[metric] == MetricAvailability.NOT_APPLICABLE }
            ) {
                return notApplicableSummary(metric, rule)
            }
            return MetricSummary(
                metric = metric,
                validFrames = 0,
                totalFrames = total,
                mean = null,
                minValue = null,
                maxValue = null,
                warningPersistence = 0.0,
                dangerPersistence = 0.0,
                severityArea = 0.0,
                contribution = 0.0,
                message = rule.message,
                status = MetricAvailability.INSUFFICIENT_DATA,
            )
        }

        return when (metric) {
            "depth_angle" -> depthSummary(metric, rule, values, total)
            "trunk_tibia" -> trunkTibiaSummary(metric, rule, values, total)
            else -> genericSummary(metric, rule, values, total)
        }
    }

    private fun genericSummary(metric: String, rule: MetricRule, values: List<Double>, total: Int): MetricSummary {
        val warnExcess: List<Double>
        val dangerHits: Int
        val warnHits: Int
        val scale: Double
        if (rule.lowerIsWorse) {
            warnExcess = values.map { max(0.0, rule.warn - it) }
            dangerHits = values.count { it <= rule.danger }
            warnHits = values.count { it <= rule.warn }
            scale = abs(rule.warn - rule.danger) + 1e-6
        } else {
            warnExcess = values.map { max(0.0, it - rule.warn) }
            dangerHits = values.count { it >= rule.danger }
            warnHits = values.count { it >= rule.warn }
            scale = abs(rule.danger - rule.warn) + 1e-6
        }

        val warningPersistence = warnHits.toDouble() / total
        val dangerPersistence = dangerHits.toDouble() / total
        val severityArea = warnExcess.sum() / scale / total
        val contribution = rule.weight * min(1.0, warningPersistence + severityArea + dangerPersistence)

        return MetricSummary(
            metric = metric,
            validFrames = values.size,
            totalFrames = total,
            mean = values.average(),
            minValue = values.min(),
            maxValue = values.max(),
            warningPersistence = warningPersistence,
            dangerPersistence = dangerPersistence,
            severityArea = severityArea,
            contribution = contribution,
            message = rule.message,
        )
    }

    /** Mirrors `_depth_summary`: scores off the rep's bottom (minimum) knee angle, not per-frame transition samples. */
    private fun depthSummary(metric: String, rule: MetricRule, values: List<Double>, total: Int): MetricSummary {
        val bottomAngle = values.min()
        var warningPersistence = 0.0
        var dangerPersistence = 0.0
        var severityArea = 0.0
        var contribution = 0.0
        if (bottomAngle > rule.warn) {
            warningPersistence = 1.0
            dangerPersistence = if (bottomAngle >= rule.danger) 1.0 else 0.0
            val scale = abs(rule.danger - rule.warn) + 1e-6
            severityArea = (bottomAngle - rule.warn) / scale
            contribution = rule.weight * min(1.0, warningPersistence + severityArea + dangerPersistence)
        }

        return MetricSummary(
            metric = metric,
            validFrames = values.size,
            totalFrames = total,
            mean = values.average(),
            minValue = bottomAngle,
            maxValue = values.max(),
            warningPersistence = warningPersistence,
            dangerPersistence = dangerPersistence,
            severityArea = severityArea,
            contribution = contribution,
            message = rule.message,
        )
    }

    /** Mirrors `_trunk_tibia_summary`: picks whichever direction (forward-lean vs. knee-dominant) contributed more. */
    private fun trunkTibiaSummary(metric: String, rule: MetricRule, values: List<Double>, total: Int): MetricSummary {
        val posWarnHits = values.count { it >= SquatThresholds.TRUNK_LEAN_W }
        val posDangerHits = values.count { it >= SquatThresholds.TRUNK_LEAN_D }
        val posScale = abs(SquatThresholds.TRUNK_LEAN_D - SquatThresholds.TRUNK_LEAN_W) + 1e-6
        val posSeverity = values.sumOf { max(0.0, it - SquatThresholds.TRUNK_LEAN_W) / posScale } / total
        val posWarning = posWarnHits.toDouble() / total
        val posDanger = posDangerHits.toDouble() / total
        val posContribution = rule.weight * min(1.0, posWarning + posSeverity + posDanger)

        val negWarnHits = values.count { it <= SquatThresholds.TRUNK_KNEE_W }
        val negDangerHits = values.count { it <= SquatThresholds.TRUNK_KNEE_D }
        val negScale = abs(SquatThresholds.TRUNK_KNEE_W - SquatThresholds.TRUNK_KNEE_D) + 1e-6
        val negSeverity = values.sumOf { max(0.0, SquatThresholds.TRUNK_KNEE_W - it) / negScale } / total
        val negWarning = negWarnHits.toDouble() / total
        val negDanger = negDangerHits.toDouble() / total
        val negContribution = rule.weight * min(1.0, negWarning + negSeverity + negDanger)

        val warningPersistence: Double
        val dangerPersistence: Double
        val severityArea: Double
        val contribution: Double
        val message: String
        if (negContribution > posContribution) {
            warningPersistence = negWarning
            dangerPersistence = negDanger
            severityArea = negSeverity
            contribution = negContribution
            message = TRUNK_TIBIA_KNEE_DOMINANT_MESSAGE
        } else {
            warningPersistence = posWarning
            dangerPersistence = posDanger
            severityArea = posSeverity
            contribution = posContribution
            message = rule.message
        }

        return MetricSummary(
            metric = metric,
            validFrames = values.size,
            totalFrames = total,
            mean = values.average(),
            minValue = values.min(),
            maxValue = values.max(),
            warningPersistence = warningPersistence,
            dangerPersistence = dangerPersistence,
            severityArea = severityArea,
            contribution = contribution,
            message = message,
        )
    }

    /** Mirrors `_not_applicable_summary`. */
    private fun notApplicableSummary(metric: String, rule: MetricRule): MetricSummary = MetricSummary(
        metric = metric,
        validFrames = 0,
        totalFrames = frames.size,
        mean = null,
        minValue = null,
        maxValue = null,
        warningPersistence = 0.0,
        dangerPersistence = 0.0,
        severityArea = 0.0,
        contribution = 0.0,
        message = rule.message,
        status = MetricAvailability.NOT_APPLICABLE,
    )

    /** Mirrors `finalize`. */
    fun finalize(): RepRecord {
        if (frames.isEmpty()) {
            return RepRecord(
                repNumber = repNumber,
                grade = RepGrade.BAD,
                minKneeAngleDeg = 180.0,
                issues = emptyMap(),
                issueMessages = emptyMap(),
                score = 0,
                primaryCorrection = "Pose visibility too low to grade reliably",
                secondaryCorrections = emptyList(),
                confidenceCoverage = 0.0,
                metricSummaries = emptyMap(),
            )
        }

        val confidence = frames.map { it.visibilityCoverage }.average()
        val kneeAngles = frames.mapNotNull { it.trackingKneeAngleDeg }
        val minKneeAngle = kneeAngles.minOrNull() ?: 180.0

        val applicableMetrics = VIEW_METRICS[view]?.toSet() ?: emptySet()
        val summaries = linkedMapOf<String, MetricSummary>()
        for ((metric, rule) in METRIC_RULES) {
            summaries[metric] = if (metric in applicableMetrics) {
                metricSummary(metric, rule)
            } else {
                notApplicableSummary(metric, rule)
            }
        }

        var totalPenalty = summaries.values.sumOf { it.contribution }
        if (confidence < 0.4) totalPenalty = max(totalPenalty, 55.0)

        val severeFault = summaries.values.any { it.dangerPersistence >= 0.25 }
        if (severeFault) totalPenalty = max(totalPenalty, 55.0)

        val score = max(0, min(100, Math.rint(100.0 - totalPenalty).toInt()))

        val grade: RepGrade
        val primary: String
        when {
            confidence < 0.4 -> {
                grade = RepGrade.BAD
                primary = "Pose visibility too low to grade reliably"
            }
            score < 55 || severeFault -> {
                grade = RepGrade.BAD
                primary = primaryMessage(summaries)
            }
            score < 80 || summaries.values.any { it.warningPersistence >= 0.35 } -> {
                grade = RepGrade.FAIR
                primary = primaryMessage(summaries)
            }
            else -> {
                grade = RepGrade.GOOD
                primary = "Good form"
            }
        }

        val secondary = secondaryMessages(summaries, primary)
        val issueMessages = summaries.filterValues { it.contribution > 0.0 }.mapValues { it.value.message }
        val issues = summaries.filterValues { it.contribution > 0.0 }.mapValues {
            if (it.value.dangerPersistence >= 0.25) DangerLevel.DANGER else DangerLevel.WARNING
        }

        return RepRecord(
            repNumber = repNumber,
            grade = grade,
            minKneeAngleDeg = minKneeAngle,
            issues = issues,
            issueMessages = issueMessages,
            score = score,
            primaryCorrection = primary,
            secondaryCorrections = secondary,
            confidenceCoverage = confidence,
            metricSummaries = summaries,
        )
    }

    /** Mirrors `_primary_message`. */
    private fun primaryMessage(summaries: Map<String, MetricSummary>): String {
        val contributors = summaries.values.filter { it.contribution > 0.0 }
        if (contributors.isEmpty()) return "Good form"
        return contributors.sortedByDescending { it.contribution }.first().message
    }

    /** Mirrors `_secondary_messages`. */
    private fun secondaryMessages(summaries: Map<String, MetricSummary>, primary: String): List<String> {
        val contributors = summaries.values
            .filter { it.contribution > 0.0 && it.message != primary }
            .sortedByDescending { it.contribution }
        val seen = mutableListOf<String>()
        for (summary in contributors) {
            if (summary.message !in seen) seen.add(summary.message)
            if (seen.size == 2) break
        }
        return seen
    }
}
